/* soapStub.h
   Generated by gSOAP 2.8.14 from webservice.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://localhost/bossn"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__Exchange
#define SOAP_TYPE__ns1__Exchange (8)
/* ns1:Exchange */
class SOAP_CMAC _ns1__Exchange
{
public:
	std::string param;	/* required element of type xsd:string */
	std::string platformId;	/* required element of type xsd:string */
	std::string RFID_USCOREUID;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE__ns1__Exchange */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__Exchange() { _ns1__Exchange::soap_default(NULL); }
	virtual ~_ns1__Exchange() { }
};
#endif

#ifndef SOAP_TYPE__ns1__ExchangeResponse
#define SOAP_TYPE__ns1__ExchangeResponse (9)
/* ns1:ExchangeResponse */
class SOAP_CMAC _ns1__ExchangeResponse
{
public:
	std::string return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE__ns1__ExchangeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__ExchangeResponse() { _ns1__ExchangeResponse::soap_default(NULL); }
	virtual ~_ns1__ExchangeResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__Accept
#define SOAP_TYPE__ns1__Accept (10)
/* ns1:Accept */
class SOAP_CMAC _ns1__Accept
{
public:
	bool flag;	/* required element of type xsd:boolean */
	std::string platformId;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE__ns1__Accept */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__Accept() { _ns1__Accept::soap_default(NULL); }
	virtual ~_ns1__Accept() { }
};
#endif

#ifndef SOAP_TYPE__ns1__AcceptResponse
#define SOAP_TYPE__ns1__AcceptResponse (11)
/* ns1:AcceptResponse */
class SOAP_CMAC _ns1__AcceptResponse
{
public:
	std::string return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE__ns1__AcceptResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__AcceptResponse() { _ns1__AcceptResponse::soap_default(NULL); }
	virtual ~_ns1__AcceptResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__ExchangeResponse
#define SOAP_TYPE___ns1__ExchangeResponse (18)
/* Operation wrapper: */
struct __ns1__ExchangeResponse
{
public:
	_ns1__ExchangeResponse *ns1__ExchangeResponse;	/* optional element of type ns1:ExchangeResponse */
public:
	int soap_type() const { return 18; } /* = unique id SOAP_TYPE___ns1__ExchangeResponse */
};
#endif

#ifndef SOAP_TYPE___ns1__Exchange
#define SOAP_TYPE___ns1__Exchange (21)
/* Operation wrapper: */
struct __ns1__Exchange
{
public:
	_ns1__Exchange *ns1__Exchange;	/* optional element of type ns1:Exchange */
public:
	int soap_type() const { return 21; } /* = unique id SOAP_TYPE___ns1__Exchange */
};
#endif

#ifndef SOAP_TYPE___ns1__AcceptResponse
#define SOAP_TYPE___ns1__AcceptResponse (24)
/* Operation wrapper: */
struct __ns1__AcceptResponse
{
public:
	_ns1__AcceptResponse *ns1__AcceptResponse;	/* optional element of type ns1:AcceptResponse */
public:
	int soap_type() const { return 24; } /* = unique id SOAP_TYPE___ns1__AcceptResponse */
};
#endif

#ifndef SOAP_TYPE___ns1__Accept
#define SOAP_TYPE___ns1__Accept (27)
/* Operation wrapper: */
struct __ns1__Accept
{
public:
	_ns1__Accept *ns1__Accept;	/* optional element of type ns1:Accept */
public:
	int soap_type() const { return 27; } /* = unique id SOAP_TYPE___ns1__Accept */
};
#endif

#ifndef SOAP_TYPE___ns1__ExchangeResponse_
#define SOAP_TYPE___ns1__ExchangeResponse_ (29)
/* Operation wrapper: */
struct __ns1__ExchangeResponse_
{
public:
	_ns1__ExchangeResponse *ns1__ExchangeResponse;	/* optional element of type ns1:ExchangeResponse */
public:
	int soap_type() const { return 29; } /* = unique id SOAP_TYPE___ns1__ExchangeResponse_ */
};
#endif

#ifndef SOAP_TYPE___ns1__Exchange_
#define SOAP_TYPE___ns1__Exchange_ (31)
/* Operation wrapper: */
struct __ns1__Exchange_
{
public:
	_ns1__Exchange *ns1__Exchange;	/* optional element of type ns1:Exchange */
public:
	int soap_type() const { return 31; } /* = unique id SOAP_TYPE___ns1__Exchange_ */
};
#endif

#ifndef SOAP_TYPE___ns1__AcceptResponse_
#define SOAP_TYPE___ns1__AcceptResponse_ (33)
/* Operation wrapper: */
struct __ns1__AcceptResponse_
{
public:
	_ns1__AcceptResponse *ns1__AcceptResponse;	/* optional element of type ns1:AcceptResponse */
public:
	int soap_type() const { return 33; } /* = unique id SOAP_TYPE___ns1__AcceptResponse_ */
};
#endif

#ifndef SOAP_TYPE___ns1__Accept_
#define SOAP_TYPE___ns1__Accept_ (35)
/* Operation wrapper: */
struct __ns1__Accept_
{
public:
	_ns1__Accept *ns1__Accept;	/* optional element of type ns1:Accept */
public:
	int soap_type() const { return 35; } /* = unique id SOAP_TYPE___ns1__Accept_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (36)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 36; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (37)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 37; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (39)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 39; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (41)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 41; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 42; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
