// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* webservice.h
   Generated by wsdl2h 2.8.14 from webservice.wsdl and typemap.dat
   2013-04-23 07:10:55 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on webservice.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://localhost                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://localhost"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://localhost"
//gsoap ns1   schema namespace:	http://localhost
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class _ns1__Hello.
class _ns1__Hello;

//  Forward declaration of class _ns1__HelloResponse.
class _ns1__HelloResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://localhost                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://localhost                                                         *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://localhost":Hello

/// "http://localhost":Hello is a complexType.
/// class _ns1__Hello operations:
/// - soap_new__ns1__Hello(soap*) allocate
/// - soap_new__ns1__Hello(soap*, int num) allocate array
/// - soap_new_req__ns1__Hello(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__Hello(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__Hello(soap*, _ns1__Hello*) deserialize from a stream
/// - int soap_write__ns1__Hello(soap, _ns1__Hello*) serialize to a stream
class _ns1__Hello
{ public:
/// Element param of type xs:string.
    std::string                          param                          1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost":HelloResponse

/// "http://localhost":HelloResponse is a complexType.
/// class _ns1__HelloResponse operations:
/// - soap_new__ns1__HelloResponse(soap*) allocate
/// - soap_new__ns1__HelloResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__HelloResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__HelloResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__HelloResponse(soap*, _ns1__HelloResponse*) deserialize from a stream
/// - int soap_write__ns1__HelloResponse(soap, _ns1__HelloResponse*) serialize to a stream
class _ns1__HelloResponse
{ public:
/// Element return of type xs:string.
    std::string                          return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://localhost                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://localhost                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	TestSoapBinding 
//gsoap ns1  service type:	TestPortType 
//gsoap ns1  service port:	http://localhost/boss/ws/test.1cws 
//gsoap ns1  service namespace:	http://localhost 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Test Definitions

@section Test_bindings Service Bindings

  - @ref TestSoapBinding

@section Test_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page TestSoapBinding Binding "TestSoapBinding"

@section TestSoap_port Port Documentation "TestSoap"
 
				<wsi:Claim xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"
						conformsTo="http://ws-i.org/profiles/basic/1.1"/>
			

@section TestSoapBinding_operations Operations of Binding  "TestSoapBinding"

  - @ref __ns1__Hello

  - @ref __ns1__Hello_

@section TestSoapBinding_ports Endpoints of Binding  "TestSoapBinding"

  - http://localhost/boss/ws/test.1cws

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   TestSoapBinding                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Hello                                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Hello" of service binding "TestSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost#Test:Hello"

  - Addressing input action: "http://localhost#Test:Hello"

  - Addressing output action: "http://localhost#Test:HelloResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Hello(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Hello*                        ns1__Hello,
    // output parameters:
    _ns1__HelloResponse*                ns1__HelloResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Hello(
    struct soap *soap,
    // input parameters:
    _ns1__Hello*                        ns1__Hello,
    // output parameters:
    _ns1__HelloResponse*                ns1__HelloResponse
  );
@endcode

C++ proxy class (defined in soapTestSoapBindingProxy.h):
@code
  class TestSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapTestSoapBindingService.h):
@code
  class TestSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	HelloResponse SOAP
//gsoap ns1  service method-style:	HelloResponse document
//gsoap ns1  service method-encoding:	HelloResponse literal
//gsoap ns1  service method-action:	HelloResponse http://localhost#Test:HelloResponse
/// Operation response "__ns1__HelloResponse" of operation "__ns1__Hello"
int __ns1__HelloResponse(
    _ns1__HelloResponse*                ns1__HelloResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Hello SOAP
//gsoap ns1  service method-style:	Hello document
//gsoap ns1  service method-encoding:	Hello literal
//gsoap ns1  service method-input-action:	Hello http://localhost#Test:Hello
//gsoap ns1  service method-output-action:	Hello http://localhost#Test:HelloResponse
int __ns1__Hello(
    _ns1__Hello*                        ns1__Hello,	///< Input parameter
    _ns1__HelloResponse*                ns1__HelloResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Hello_                                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Hello_" of service binding "TestSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost#Test:Hello"

  - Addressing input action: "http://localhost#Test:Hello"

  - Addressing output action: "http://localhost#Test:HelloResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Hello_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Hello*                        ns1__Hello,
    // output parameters:
    _ns1__HelloResponse*                ns1__HelloResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Hello_(
    struct soap *soap,
    // input parameters:
    _ns1__Hello*                        ns1__Hello,
    // output parameters:
    _ns1__HelloResponse*                ns1__HelloResponse
  );
@endcode

C++ proxy class (defined in soapTestSoapBindingProxy.h):
@code
  class TestSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapTestSoapBindingService.h):
@code
  class TestSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	HelloResponse_ SOAP
//gsoap ns1  service method-style:	HelloResponse_ document
//gsoap ns1  service method-encoding:	HelloResponse_ literal
//gsoap ns1  service method-action:	HelloResponse_ http://localhost#Test:HelloResponse
/// Operation response "__ns1__HelloResponse_" of operation "__ns1__Hello_"
int __ns1__HelloResponse_(
    _ns1__HelloResponse*                ns1__HelloResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Hello_ SOAP
//gsoap ns1  service method-style:	Hello_ document
//gsoap ns1  service method-encoding:	Hello_ literal
//gsoap ns1  service method-input-action:	Hello_ http://localhost#Test:Hello
//gsoap ns1  service method-output-action:	Hello_ http://localhost#Test:HelloResponse
int __ns1__Hello_(
    _ns1__Hello*                        ns1__Hello,	///< Input parameter
    _ns1__HelloResponse*                ns1__HelloResponse	///< Output parameter
);

/**

@page TestSoapBinding Binding "TestSoapBinding"

@section TestSoapBinding_policy_enablers Policy Enablers of Binding  "TestSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://localhost"

  - <ns1:Hello> @ref _ns1__Hello
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__Hello(struct soap*, _ns1__Hello*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__Hello(struct soap*, _ns1__Hello*);
    @endcode

  - <ns1:HelloResponse> @ref _ns1__HelloResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__HelloResponse(struct soap*, _ns1__HelloResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__HelloResponse(struct soap*, _ns1__HelloResponse*);
    @endcode

*/

/* End of webservice.h */
