// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* webservice.h
   Generated by wsdl2h 2.8.14 from webservice.wsdl and typemap.dat
   2013-08-24 09:12:28 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on webservice.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://localhost/bossn                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://localhost/bossn"
ns2 = "http://www.skifcorp.com.ua"

*/

#define SOAP_NAMESPACE_OF_ns2	"http://www.skifcorp.com.ua"
//gsoap ns2   schema namespace:	http://www.skifcorp.com.ua
//gsoap ns2   schema elementForm:	qualified
//gsoap ns2   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns1	"http://localhost/bossn"
//gsoap ns1   schema namespace:	http://localhost/bossn
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns2__TagsList.
class ns2__TagsList;

//  Forward declaration of class _ns1__Appeared.
class _ns1__Appeared;

//  Forward declaration of class _ns1__AppearedResponse.
class _ns1__AppearedResponse;

//  Forward declaration of class _ns1__Exchange.
class _ns1__Exchange;

//  Forward declaration of class _ns1__ExchangeResponse.
class _ns1__ExchangeResponse;

//  Forward declaration of class _ns1__Accept.
class _ns1__Accept;

//  Forward declaration of class _ns1__AcceptResponse.
class _ns1__AcceptResponse;

//  Forward declaration of class _ns1__Disappeared.
class _ns1__Disappeared;

//  Forward declaration of class _ns1__DisappearedResponse.
class _ns1__DisappearedResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.skifcorp.com.ua                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://localhost/bossn                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.skifcorp.com.ua                                               *
 *                                                                            *
\******************************************************************************/


/// "http://www.skifcorp.com.ua":TagsList is a complexType.
/// class ns2__TagsList operations:
/// - soap_new_ns2__TagsList(soap*) allocate
/// - soap_new_ns2__TagsList(soap*, int num) allocate array
/// - soap_new_req_ns2__TagsList(soap*, ...) allocate, set required members
/// - soap_new_set_ns2__TagsList(soap*, ...) allocate, set all public members
/// - int soap_read_ns2__TagsList(soap*, ns2__TagsList*) deserialize from a stream
/// - int soap_write_ns2__TagsList(soap, ns2__TagsList*) serialize to a stream
class ns2__TagsList
{ public:
/// Element tags of type xs:string.
    std::string                          tags                           1;	///< Required element.
/// Element additional of type xs:string.
    std::string                          additional                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://localhost/bossn                                                   *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://localhost/bossn":Appeared

/// "http://localhost/bossn":Appeared is a complexType.
/// class _ns1__Appeared operations:
/// - soap_new__ns1__Appeared(soap*) allocate
/// - soap_new__ns1__Appeared(soap*, int num) allocate array
/// - soap_new_req__ns1__Appeared(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__Appeared(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__Appeared(soap*, _ns1__Appeared*) deserialize from a stream
/// - int soap_write__ns1__Appeared(soap, _ns1__Appeared*) serialize to a stream
class _ns1__Appeared
{ public:
/// Element platformId of type xs:string.
    std::string                          platformId                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":AppearedResponse

/// "http://localhost/bossn":AppearedResponse is a complexType.
/// class _ns1__AppearedResponse operations:
/// - soap_new__ns1__AppearedResponse(soap*) allocate
/// - soap_new__ns1__AppearedResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__AppearedResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__AppearedResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__AppearedResponse(soap*, _ns1__AppearedResponse*) deserialize from a stream
/// - int soap_write__ns1__AppearedResponse(soap, _ns1__AppearedResponse*) serialize to a stream
class _ns1__AppearedResponse
{ public:
/// Element return of type xs:boolean.
    bool                                 return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":Exchange

/// "http://localhost/bossn":Exchange is a complexType.
/// class _ns1__Exchange operations:
/// - soap_new__ns1__Exchange(soap*) allocate
/// - soap_new__ns1__Exchange(soap*, int num) allocate array
/// - soap_new_req__ns1__Exchange(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__Exchange(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__Exchange(soap*, _ns1__Exchange*) deserialize from a stream
/// - int soap_write__ns1__Exchange(soap, _ns1__Exchange*) serialize to a stream
class _ns1__Exchange
{ public:
/// Element param of type xs:string.
    std::string                          param                          1;	///< Required element.
/// Element platformId of type xs:string.
    std::string                          platformId                     1;	///< Required element.
/// Element RFID_UID of type xs:string.
    std::string                          RFID_USCOREUID                 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":ExchangeResponse

/// "http://localhost/bossn":ExchangeResponse is a complexType.
/// class _ns1__ExchangeResponse operations:
/// - soap_new__ns1__ExchangeResponse(soap*) allocate
/// - soap_new__ns1__ExchangeResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__ExchangeResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__ExchangeResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__ExchangeResponse(soap*, _ns1__ExchangeResponse*) deserialize from a stream
/// - int soap_write__ns1__ExchangeResponse(soap, _ns1__ExchangeResponse*) serialize to a stream
class _ns1__ExchangeResponse
{ public:
/// Element return of type "http://www.skifcorp.com.ua":TagsList.
    ns2__TagsList*                       return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":Accept

/// "http://localhost/bossn":Accept is a complexType.
/// class _ns1__Accept operations:
/// - soap_new__ns1__Accept(soap*) allocate
/// - soap_new__ns1__Accept(soap*, int num) allocate array
/// - soap_new_req__ns1__Accept(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__Accept(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__Accept(soap*, _ns1__Accept*) deserialize from a stream
/// - int soap_write__ns1__Accept(soap, _ns1__Accept*) serialize to a stream
class _ns1__Accept
{ public:
/// Element flag of type xs:boolean.
    bool                                 flag                           1;	///< Required element.
/// Element platformId of type xs:string.
    std::string                          platformId                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":AcceptResponse

/// "http://localhost/bossn":AcceptResponse is a complexType.
/// class _ns1__AcceptResponse operations:
/// - soap_new__ns1__AcceptResponse(soap*) allocate
/// - soap_new__ns1__AcceptResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__AcceptResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__AcceptResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__AcceptResponse(soap*, _ns1__AcceptResponse*) deserialize from a stream
/// - int soap_write__ns1__AcceptResponse(soap, _ns1__AcceptResponse*) serialize to a stream
class _ns1__AcceptResponse
{ public:
/// Element return of type xs:string.
    std::string                          return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":Disappeared

/// "http://localhost/bossn":Disappeared is a complexType.
/// class _ns1__Disappeared operations:
/// - soap_new__ns1__Disappeared(soap*) allocate
/// - soap_new__ns1__Disappeared(soap*, int num) allocate array
/// - soap_new_req__ns1__Disappeared(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__Disappeared(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__Disappeared(soap*, _ns1__Disappeared*) deserialize from a stream
/// - int soap_write__ns1__Disappeared(soap, _ns1__Disappeared*) serialize to a stream
class _ns1__Disappeared
{ public:
/// Element platformId of type xs:string.
    std::string                          platformId                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "http://localhost/bossn":DisappearedResponse

/// "http://localhost/bossn":DisappearedResponse is a complexType.
/// class _ns1__DisappearedResponse operations:
/// - soap_new__ns1__DisappearedResponse(soap*) allocate
/// - soap_new__ns1__DisappearedResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__DisappearedResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__DisappearedResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__DisappearedResponse(soap*, _ns1__DisappearedResponse*) deserialize from a stream
/// - int soap_write__ns1__DisappearedResponse(soap, _ns1__DisappearedResponse*) serialize to a stream
class _ns1__DisappearedResponse
{ public:
/// Element return of type xs:boolean.
    bool                                 return_                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.skifcorp.com.ua                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.skifcorp.com.ua                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://localhost/bossn                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://localhost/bossn                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	bossnSoapBinding 
//gsoap ns1  service type:	bossnPortType 
//gsoap ns1  service port:	http://192.168.0.17/bossn/ws/bossn.1cws 
//gsoap ns1  service namespace:	http://localhost/bossn 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage bossn Definitions

@section bossn_bindings Service Bindings

  - @ref bossnSoapBinding

@section bossn_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page bossnSoapBinding Binding "bossnSoapBinding"

@section bossnSoap_port Port Documentation "bossnSoap"
<wsi:Claim xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" conformsTo="http://ws-i.org/profiles/basic/1.1"/>


@section bossnSoapBinding_operations Operations of Binding  "bossnSoapBinding"

  - @ref __ns1__Appeared

  - @ref __ns1__Exchange

  - @ref __ns1__Accept

  - @ref __ns1__Disappeared

  - @ref __ns1__Appeared_

  - @ref __ns1__Exchange_

  - @ref __ns1__Accept_

  - @ref __ns1__Disappeared_

@section bossnSoapBinding_ports Endpoints of Binding  "bossnSoapBinding"

  - http://192.168.0.17/bossn/ws/bossn.1cws

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   bossnSoapBinding                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Appeared                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Appeared" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Appeared"

  - Addressing input action: "http://localhost/bossn#bossn:Appeared"

  - Addressing output action: "http://localhost/bossn#bossn:AppearedResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Appeared(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Appeared*                     ns1__Appeared,
    // output parameters:
    _ns1__AppearedResponse*             ns1__AppearedResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Appeared(
    struct soap *soap,
    // input parameters:
    _ns1__Appeared*                     ns1__Appeared,
    // output parameters:
    _ns1__AppearedResponse*             ns1__AppearedResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	AppearedResponse SOAP
//gsoap ns1  service method-style:	AppearedResponse document
//gsoap ns1  service method-encoding:	AppearedResponse literal
//gsoap ns1  service method-action:	AppearedResponse http://localhost/bossn#bossn:AppearedResponse
/// Operation response "__ns1__AppearedResponse" of operation "__ns1__Appeared"
int __ns1__AppearedResponse(
    _ns1__AppearedResponse*             ns1__AppearedResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Appeared SOAP
//gsoap ns1  service method-style:	Appeared document
//gsoap ns1  service method-encoding:	Appeared literal
//gsoap ns1  service method-input-action:	Appeared http://localhost/bossn#bossn:Appeared
//gsoap ns1  service method-output-action:	Appeared http://localhost/bossn#bossn:AppearedResponse
int __ns1__Appeared(
    _ns1__Appeared*                     ns1__Appeared,	///< Input parameter
    _ns1__AppearedResponse*             ns1__AppearedResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Exchange                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Exchange" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Exchange"

  - Addressing input action: "http://localhost/bossn#bossn:Exchange"

  - Addressing output action: "http://localhost/bossn#bossn:ExchangeResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Exchange(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Exchange*                     ns1__Exchange,
    // output parameters:
    _ns1__ExchangeResponse*             ns1__ExchangeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Exchange(
    struct soap *soap,
    // input parameters:
    _ns1__Exchange*                     ns1__Exchange,
    // output parameters:
    _ns1__ExchangeResponse*             ns1__ExchangeResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ExchangeResponse SOAP
//gsoap ns1  service method-style:	ExchangeResponse document
//gsoap ns1  service method-encoding:	ExchangeResponse literal
//gsoap ns1  service method-action:	ExchangeResponse http://localhost/bossn#bossn:ExchangeResponse
/// Operation response "__ns1__ExchangeResponse" of operation "__ns1__Exchange"
int __ns1__ExchangeResponse(
    _ns1__ExchangeResponse*             ns1__ExchangeResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Exchange SOAP
//gsoap ns1  service method-style:	Exchange document
//gsoap ns1  service method-encoding:	Exchange literal
//gsoap ns1  service method-input-action:	Exchange http://localhost/bossn#bossn:Exchange
//gsoap ns1  service method-output-action:	Exchange http://localhost/bossn#bossn:ExchangeResponse
int __ns1__Exchange(
    _ns1__Exchange*                     ns1__Exchange,	///< Input parameter
    _ns1__ExchangeResponse*             ns1__ExchangeResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Accept                                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Accept" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Accept"

  - Addressing input action: "http://localhost/bossn#bossn:Accept"

  - Addressing output action: "http://localhost/bossn#bossn:AcceptResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Accept(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Accept*                       ns1__Accept,
    // output parameters:
    _ns1__AcceptResponse*               ns1__AcceptResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Accept(
    struct soap *soap,
    // input parameters:
    _ns1__Accept*                       ns1__Accept,
    // output parameters:
    _ns1__AcceptResponse*               ns1__AcceptResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	AcceptResponse SOAP
//gsoap ns1  service method-style:	AcceptResponse document
//gsoap ns1  service method-encoding:	AcceptResponse literal
//gsoap ns1  service method-action:	AcceptResponse http://localhost/bossn#bossn:AcceptResponse
/// Operation response "__ns1__AcceptResponse" of operation "__ns1__Accept"
int __ns1__AcceptResponse(
    _ns1__AcceptResponse*               ns1__AcceptResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Accept SOAP
//gsoap ns1  service method-style:	Accept document
//gsoap ns1  service method-encoding:	Accept literal
//gsoap ns1  service method-input-action:	Accept http://localhost/bossn#bossn:Accept
//gsoap ns1  service method-output-action:	Accept http://localhost/bossn#bossn:AcceptResponse
int __ns1__Accept(
    _ns1__Accept*                       ns1__Accept,	///< Input parameter
    _ns1__AcceptResponse*               ns1__AcceptResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Disappeared                                                       *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Disappeared" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Disappeared"

  - Addressing input action: "http://localhost/bossn#bossn:Disappeared"

  - Addressing output action: "http://localhost/bossn#bossn:DisappearedResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Disappeared(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Disappeared*                  ns1__Disappeared,
    // output parameters:
    _ns1__DisappearedResponse*          ns1__DisappearedResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Disappeared(
    struct soap *soap,
    // input parameters:
    _ns1__Disappeared*                  ns1__Disappeared,
    // output parameters:
    _ns1__DisappearedResponse*          ns1__DisappearedResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	DisappearedResponse SOAP
//gsoap ns1  service method-style:	DisappearedResponse document
//gsoap ns1  service method-encoding:	DisappearedResponse literal
//gsoap ns1  service method-action:	DisappearedResponse http://localhost/bossn#bossn:DisappearedResponse
/// Operation response "__ns1__DisappearedResponse" of operation "__ns1__Disappeared"
int __ns1__DisappearedResponse(
    _ns1__DisappearedResponse*          ns1__DisappearedResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Disappeared SOAP
//gsoap ns1  service method-style:	Disappeared document
//gsoap ns1  service method-encoding:	Disappeared literal
//gsoap ns1  service method-input-action:	Disappeared http://localhost/bossn#bossn:Disappeared
//gsoap ns1  service method-output-action:	Disappeared http://localhost/bossn#bossn:DisappearedResponse
int __ns1__Disappeared(
    _ns1__Disappeared*                  ns1__Disappeared,	///< Input parameter
    _ns1__DisappearedResponse*          ns1__DisappearedResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Appeared_                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Appeared_" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Appeared"

  - Addressing input action: "http://localhost/bossn#bossn:Appeared"

  - Addressing output action: "http://localhost/bossn#bossn:AppearedResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Appeared_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Appeared*                     ns1__Appeared,
    // output parameters:
    _ns1__AppearedResponse*             ns1__AppearedResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Appeared_(
    struct soap *soap,
    // input parameters:
    _ns1__Appeared*                     ns1__Appeared,
    // output parameters:
    _ns1__AppearedResponse*             ns1__AppearedResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	AppearedResponse_ SOAP
//gsoap ns1  service method-style:	AppearedResponse_ document
//gsoap ns1  service method-encoding:	AppearedResponse_ literal
//gsoap ns1  service method-action:	AppearedResponse_ http://localhost/bossn#bossn:AppearedResponse
/// Operation response "__ns1__AppearedResponse_" of operation "__ns1__Appeared_"
int __ns1__AppearedResponse_(
    _ns1__AppearedResponse*             ns1__AppearedResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Appeared_ SOAP
//gsoap ns1  service method-style:	Appeared_ document
//gsoap ns1  service method-encoding:	Appeared_ literal
//gsoap ns1  service method-input-action:	Appeared_ http://localhost/bossn#bossn:Appeared
//gsoap ns1  service method-output-action:	Appeared_ http://localhost/bossn#bossn:AppearedResponse
int __ns1__Appeared_(
    _ns1__Appeared*                     ns1__Appeared,	///< Input parameter
    _ns1__AppearedResponse*             ns1__AppearedResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Exchange_                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Exchange_" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Exchange"

  - Addressing input action: "http://localhost/bossn#bossn:Exchange"

  - Addressing output action: "http://localhost/bossn#bossn:ExchangeResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Exchange_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Exchange*                     ns1__Exchange,
    // output parameters:
    _ns1__ExchangeResponse*             ns1__ExchangeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Exchange_(
    struct soap *soap,
    // input parameters:
    _ns1__Exchange*                     ns1__Exchange,
    // output parameters:
    _ns1__ExchangeResponse*             ns1__ExchangeResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ExchangeResponse_ SOAP
//gsoap ns1  service method-style:	ExchangeResponse_ document
//gsoap ns1  service method-encoding:	ExchangeResponse_ literal
//gsoap ns1  service method-action:	ExchangeResponse_ http://localhost/bossn#bossn:ExchangeResponse
/// Operation response "__ns1__ExchangeResponse_" of operation "__ns1__Exchange_"
int __ns1__ExchangeResponse_(
    _ns1__ExchangeResponse*             ns1__ExchangeResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Exchange_ SOAP
//gsoap ns1  service method-style:	Exchange_ document
//gsoap ns1  service method-encoding:	Exchange_ literal
//gsoap ns1  service method-input-action:	Exchange_ http://localhost/bossn#bossn:Exchange
//gsoap ns1  service method-output-action:	Exchange_ http://localhost/bossn#bossn:ExchangeResponse
int __ns1__Exchange_(
    _ns1__Exchange*                     ns1__Exchange,	///< Input parameter
    _ns1__ExchangeResponse*             ns1__ExchangeResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Accept_                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Accept_" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Accept"

  - Addressing input action: "http://localhost/bossn#bossn:Accept"

  - Addressing output action: "http://localhost/bossn#bossn:AcceptResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Accept_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Accept*                       ns1__Accept,
    // output parameters:
    _ns1__AcceptResponse*               ns1__AcceptResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Accept_(
    struct soap *soap,
    // input parameters:
    _ns1__Accept*                       ns1__Accept,
    // output parameters:
    _ns1__AcceptResponse*               ns1__AcceptResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	AcceptResponse_ SOAP
//gsoap ns1  service method-style:	AcceptResponse_ document
//gsoap ns1  service method-encoding:	AcceptResponse_ literal
//gsoap ns1  service method-action:	AcceptResponse_ http://localhost/bossn#bossn:AcceptResponse
/// Operation response "__ns1__AcceptResponse_" of operation "__ns1__Accept_"
int __ns1__AcceptResponse_(
    _ns1__AcceptResponse*               ns1__AcceptResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Accept_ SOAP
//gsoap ns1  service method-style:	Accept_ document
//gsoap ns1  service method-encoding:	Accept_ literal
//gsoap ns1  service method-input-action:	Accept_ http://localhost/bossn#bossn:Accept
//gsoap ns1  service method-output-action:	Accept_ http://localhost/bossn#bossn:AcceptResponse
int __ns1__Accept_(
    _ns1__Accept*                       ns1__Accept,	///< Input parameter
    _ns1__AcceptResponse*               ns1__AcceptResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Disappeared_                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Disappeared_" of service binding "bossnSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Action: "http://localhost/bossn#bossn:Disappeared"

  - Addressing input action: "http://localhost/bossn#bossn:Disappeared"

  - Addressing output action: "http://localhost/bossn#bossn:DisappearedResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Disappeared_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__Disappeared*                  ns1__Disappeared,
    // output parameters:
    _ns1__DisappearedResponse*          ns1__DisappearedResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Disappeared_(
    struct soap *soap,
    // input parameters:
    _ns1__Disappeared*                  ns1__Disappeared,
    // output parameters:
    _ns1__DisappearedResponse*          ns1__DisappearedResponse
  );
@endcode

C++ proxy class (defined in soapbossnSoapBindingProxy.h):
@code
  class bossnSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbossnSoapBindingService.h):
@code
  class bossnSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	DisappearedResponse_ SOAP
//gsoap ns1  service method-style:	DisappearedResponse_ document
//gsoap ns1  service method-encoding:	DisappearedResponse_ literal
//gsoap ns1  service method-action:	DisappearedResponse_ http://localhost/bossn#bossn:DisappearedResponse
/// Operation response "__ns1__DisappearedResponse_" of operation "__ns1__Disappeared_"
int __ns1__DisappearedResponse_(
    _ns1__DisappearedResponse*          ns1__DisappearedResponse,	///< Input parameter
    void	///< One-way message: no output parameter
);
//gsoap ns1  service method-protocol:	Disappeared_ SOAP
//gsoap ns1  service method-style:	Disappeared_ document
//gsoap ns1  service method-encoding:	Disappeared_ literal
//gsoap ns1  service method-input-action:	Disappeared_ http://localhost/bossn#bossn:Disappeared
//gsoap ns1  service method-output-action:	Disappeared_ http://localhost/bossn#bossn:DisappearedResponse
int __ns1__Disappeared_(
    _ns1__Disappeared*                  ns1__Disappeared,	///< Input parameter
    _ns1__DisappearedResponse*          ns1__DisappearedResponse	///< Output parameter
);

/**

@page bossnSoapBinding Binding "bossnSoapBinding"

@section bossnSoapBinding_policy_enablers Policy Enablers of Binding  "bossnSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema "http://www.skifcorp.com.ua"

@section ns1 Top-level root elements of schema "http://localhost/bossn"

  - <ns1:Appeared> @ref _ns1__Appeared
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__Appeared(struct soap*, _ns1__Appeared*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__Appeared(struct soap*, _ns1__Appeared*);
    @endcode

  - <ns1:AppearedResponse> @ref _ns1__AppearedResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__AppearedResponse(struct soap*, _ns1__AppearedResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__AppearedResponse(struct soap*, _ns1__AppearedResponse*);
    @endcode

  - <ns1:Exchange> @ref _ns1__Exchange
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__Exchange(struct soap*, _ns1__Exchange*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__Exchange(struct soap*, _ns1__Exchange*);
    @endcode

  - <ns1:ExchangeResponse> @ref _ns1__ExchangeResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__ExchangeResponse(struct soap*, _ns1__ExchangeResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__ExchangeResponse(struct soap*, _ns1__ExchangeResponse*);
    @endcode

  - <ns1:Accept> @ref _ns1__Accept
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__Accept(struct soap*, _ns1__Accept*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__Accept(struct soap*, _ns1__Accept*);
    @endcode

  - <ns1:AcceptResponse> @ref _ns1__AcceptResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__AcceptResponse(struct soap*, _ns1__AcceptResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__AcceptResponse(struct soap*, _ns1__AcceptResponse*);
    @endcode

  - <ns1:Disappeared> @ref _ns1__Disappeared
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__Disappeared(struct soap*, _ns1__Disappeared*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__Disappeared(struct soap*, _ns1__Disappeared*);
    @endcode

  - <ns1:DisappearedResponse> @ref _ns1__DisappearedResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__DisappearedResponse(struct soap*, _ns1__DisappearedResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__DisappearedResponse(struct soap*, _ns1__DisappearedResponse*);
    @endcode

*/

/* End of webservice.h */
